function loadLevel() {
    level1 = new Level(
        [
            new Bottle(250, 350),
            new Bottle(380, 350),
            new Bottle(580, 350),
            new Bottle(880, 350),
            new Bottle(1080, 350),
            new Bottle(1380, 350),
            new Bottle(1480, 350),
            new Bottle(1780, 350),
            new Bottle(1200, 350),
            new Bottle(2000, 350),
        ],
        [
            new SmallChicken(2200, 335),
            new SmallChicken(1300, 335),
            new SmallChicken(1550, 335),
            new Chicken(550, 320),
            new Chicken(800, 325),
            new Chicken(1200, 325),
            new Chicken(1300, 325),
            new Chicken(1800, 325),
        ],
        [
            new Endboss(),
        ],
        [
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
        ],
        [
            new Coin(380, 125),
            new Coin(430, 100),
            new Coin(480, 100),
            new Coin(530, 125),
            new Coin(800, 100),
            new Coin(1000, 100),
            new Coin(1400, 125),
            new Coin(1450, 100),
            new Coin(1500, 100),
            new Coin(1550, 125),
        ],
        [
            new BackgroundObject('img/5_background/layers/air.png', -719),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),

            new BackgroundObject('img/5_background/layers/air.png', 0),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
            new BackgroundObject('img/5_background/layers/air.png', 719),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),

            new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
            new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),
        ]
    );
}
